version: '3.8'

services:
  test_backend:
    container_name: test_backend
    image: dipeshkumarsah98/ba:backend-dev
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - test

  test_db:
    image: postgres:13.5
    container_name: test_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5421:5432'
    command: -p 5432
    networks:
      - test

  test_redis:
    container_name: test_redis
    image: redis:6.2.12
    restart: always
    ports:
      - '6379:6379'
    networks:
      - test

watchtower:
  container_name: watchtower
  image: containrrr/watchtower
  environment:
    - WATCHTOWER_CLEANUP=true

  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  command: --interval 30 test_backend


networks:
  test:
    driver: bridge

volumes:
  postgres:
    name: test-db
