version: '3.8'

services:
  prod_backend:
    container_name: prod_backend
    image: dipeshkumarsah98/ba:backend-prod
    restart: always
    ports:
      - 8000:8080
    env_file:
      - .env
    depends_on:
      - prod_db
    networks:
      - prod_network

  prod_db:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prod_db

    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - '5431:5432'
    command: -p 5432
    networks:
      - prod_network

  prod_redis:
    container_name: redis
    image: redis:6.2.12
    restart: always
    ports:
      - '6379:6379'
    networks:
      - prod_network

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command: --interval 30 prod_backend

networks:
  prod_network:
    driver: bridge

volumes:
  postgres:
    name: prod_db